# Generated by Django 4.2.18 on 2025-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, default='Lomé', max_length=255, null=True, verbose_name='Emplacement'),
        ),
    ]
