# Generated by Django 4.2.18 on 2025-09-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemviews', to='item.item', verbose_name='Article'),
        ),
    ]
