# Generated by Django 4.2.18 on 2025-06-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversationmessage_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/files/'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
